// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApiRealState.Data;

#nullable disable

namespace MinimalApiRealState.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231004133819_PropertyMigration")]
    partial class PropertyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalApiRealState.Shared.RsProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f8561e6-54c6-42b5-8a56-b605a4bb26d8"),
                            CreationDate = new DateTimeOffset(new DateTime(2023, 10, 4, 13, 38, 19, 830, DateTimeKind.Unspecified).AddTicks(3689), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Descripción test 1",
                            IsActive = true,
                            Location = "Cartagena",
                            Name = "Casa las palmas"
                        },
                        new
                        {
                            Id = new Guid("b6a1923b-b82a-48a3-9a39-bce1caf99cef"),
                            CreationDate = new DateTimeOffset(new DateTime(2023, 10, 4, 13, 38, 19, 830, DateTimeKind.Unspecified).AddTicks(3695), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Descripción test 2",
                            IsActive = true,
                            Location = "Barranquilla",
                            Name = "Casa Concorde"
                        },
                        new
                        {
                            Id = new Guid("bf54fca7-df09-42dd-a6df-c5da8c7fecfd"),
                            CreationDate = new DateTimeOffset(new DateTime(2023, 10, 4, 13, 38, 19, 830, DateTimeKind.Unspecified).AddTicks(3699), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Descripción test 3",
                            IsActive = false,
                            Location = "Bogotá",
                            Name = "Casa Centro Bogotá"
                        },
                        new
                        {
                            Id = new Guid("92e2db3d-aceb-496a-b57e-0d0cf2eae202"),
                            CreationDate = new DateTimeOffset(new DateTime(2023, 10, 4, 13, 38, 19, 830, DateTimeKind.Unspecified).AddTicks(3702), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Descripción test 4",
                            IsActive = true,
                            Location = "Medellín",
                            Name = "Casa El Poblado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
